let h = Math.random() * 360;
let s = Math.random() * 100;
let l;

function setup() {
    createCanvas(windowWidth,windowHeight);
    colorMode(HSL);
    noStroke();
}

function draw() {
    // background(0, 0, 0, 0.1);


    h = (h + 0.2) % 360;
    s = s % 100;
    l = 50;
    // background(h, s, l);

    // Creating a radial gradient centered on mouse
    let ctx = drawingContext; 
    let gradient = ctx.createRadialGradient(mouseX, mouseY, 0, mouseX, mouseY, 160);
    gradient.addColorStop(0, `hsl(${h}, ${s}%, ${l}%)`);
    gradient.addColorStop(1, `hsl(${(360 - h)}, ${s}%, ${l}%)`);
  

    ctx.fillStyle = gradient;
    ctx.fillRect(0,0, width, height);
}




// // Radial color change -- Generated by ChatGPT
// const body = document.body;

// let color1 = randomHSL();
// let color2 = randomHSL();

// function randomHSL() {
//     const h = Math.floor(Math.random() * 360);
//     const s = 100 + Math.random() * 30;
//     const l = 50 + Math.random() * 10;
//     return {h, s, l};
// }

// function hslString(c) {
//     return `hsl(${c.h}, ${c.s}%, ${c.l}%)`;
// }

// function animate() {
//     // Slowly shift hues
//     color1.h = (color1.h + 0.2) % 360;
//     color2.h = (color2.h + 0.15) % 360;

//     // Apply radial gradient
//     body.style.background = `radial-gradient(circle, ${hslString(color1)} 0%, ${hslString(color2)} 100%)`;

//     requestAnimationFrame(animate);
// }
// animate();
